### ISSUE TITLE
Extensions: Add CryptexFixup to the list

### ISSUE THREAD

**Issue by 5T33Z0** [benbaker76/Hackintool#192]
Could you add [CryptexFixup](https://github.com/acidanthera/CryptexFixup) to the list of Extensions, please? It's a relatively new kext by Acidanthera required for installing/booting macOS Ventura on pre-Haswell systems.

Thank you

**Comment by benbaker76** [comment]
Please try 3.9.2

**Comment by 5T33Z0** [comment]
Thanks. It's actually in there twice now:
![Bildschirmfoto 2023-01-10 um 19 25 32](https://user-images.githubusercontent.com/76865553/211632311-5c9313ae-4578-48cd-b763-3601810d604c.png)

**Comment by benbaker76** [comment]
3.9.3 should fix the duplicates

**Comment by 5T33Z0** [comment]
Thanks
