### ISSUE TITLE
Homebrew won't install SHA256 mismatch.

### ISSUE THREAD

**Issue by cyberfunk** [benbaker76/Hackintool#197]
Has Hackintool been hacked or something? I previously installed it with Homebrew but when I opened it for the first time I received warnings to move it to the trash and was not able to open it. I tried the various permissions fixes and Malware overides but none of them worked. I uninstalled it and now I can't install via Homebrew. I get SHA256 mismatch. Is this an error on my side or the GitHub side?
![Screen Shot 2023-06-05 at 9 19 41 PM](https://github.com/benbaker76/Hackintool/assets/12664589/e5d0b097-2b57-407c-8e96-e423c401635d)

**Comment by benbaker76** [comment]
I just did another release with a version bump that should fix this

**Comment by cyberfunk** [comment]
Ok thanks. I just went ahead and downloaded it manually from your GitHub releases just now and that installed just fine.😁
